configuration: Release
platform: Any CPU
install:
  - ps: choco install gitversion.portable -pre -y
assembly_info:
  patch: false
before_build:
- ps: >-
    nuget restore src\ValidaCNPJCore.sln

    gitversion /l console /output buildserver /updateAssemblyInfo
build:
  project: src\ValidaCNPJCore.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
  - path: src\ValidaCNPJCore\bin\Release\*.nupkg
