install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore src\ValidaCNPJCore.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: src\ValidaCNPJCore.sln
