name: Compilar Biblioteca

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configurar .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Instalar dependências
      run: dotnet restore .\src\ValidaCNPJCore.sln
    - name: Compilar
      run: dotnet build .\src\ValidaCNPJCore.sln --configuration Release --no-restore
    - name: Testar
      run: dotnet test .\src\ValidaCNPJCore.sln --no-restore --verbosity normal
